#!/usr/bin/env node
import { resolve } from 'node:path';
import { loadEnv } from './env.js';

// Load .env (cwd) / ~/.roast-my-react.env before anything reads process.env.
loadEnv();

import { Command } from 'commander';
import chalk from 'chalk';
import ora from 'ora';
import { crawl, isChromiumInstalled, installChromium } from './crawl.js';
import { detectDevServers, COMMON_PORTS, type DetectedServer } from './detect.js';
import { deriveIssues } from './issues.js';
import { roastIssues, MissingApiKeyError } from './roast.js';
import { writeReport } from './report.js';
import { findSavedAuth, runLogin } from './auth.js';
import { handOffToAgent } from './agents.js';
import { renderCard } from './card.js';
import { buildSnapshot, saveBaseline, loadBaseline, renderComparison } from './baseline.js';
import { select } from './prompt.js';
import { loadConfig, applyConfigEnv } from './config.js';
import {
  renderHeader,
  renderScores,
  renderRoasts,
  renderRawFindings,
  renderRouteSummary,
  renderWarnings,
  renderFooter,
  renderMissingKeyNotice,
} from './render.js';
import type { Findings, Issue, RoastOptions, RoastedIssue, Severity } from './types.js';

const program = new Command();

program
  .name('roast-my-react')
  .description('Brutally funny AI roasts of your React/Next.js app — with real fixes underneath.')
  .version('0.9.0')
  .option('--url <url>', 'target a running app (auto-detected if omitted)')
  .option('--report', 'generate ./roast-report.html', false)
  .option('--severity <n>', '1=gentle, 2=normal, 3=savage', '2')
  .option('--json', 'output raw findings as JSON instead of the roast', false)
  .option('--no-ai', 'skip the AI step, just show findings')
  .option('--fast', 'skip the Lighthouse audit for a much faster run', false)
  .option('--auth <file>', 'Playwright storageState JSON for auditing logged-in pages')
  .option('--header <header...>', 'extra request header, repeatable (e.g. "Authorization: Bearer x")')
  .option('--fix [agent]', 'after the roast, hand the fixes to a coding agent (claude|codex|opencode)')
  .option('--routes <list>', 'audit multiple routes, comma-separated (e.g. "/,/dashboard,/login")')
  .option('--no-card', 'skip the shareable PNG roast card (generated by default)')
  .option('--baseline', 'compare this run against the saved baseline', false)
  .option('--save-baseline', 'save this run as the baseline for future comparisons', false)
  .action(async (raw, cmd) => {
    const cwd = process.cwd();
    const json = Boolean(raw.json);

    // Precedence: CLI flag > roast.config.json > built-in default.
    const cfg = loadConfig(cwd);
    applyConfigEnv(cfg);
    const setByCli = (key: string): boolean => cmd.getOptionValueSource(key) === 'cli';
    const pickBool = (key: string, cfgVal: boolean | undefined, def: boolean): boolean =>
      setByCli(key) ? Boolean(raw[key]) : cfgVal ?? def;

    const severity = clampSeverity(
      setByCli('severity') ? raw.severity : cfg.severity !== undefined ? String(cfg.severity) : raw.severity
    );

    // Resolve the target URL: --url > config.url > auto-detect.
    const explicitUrl = setByCli('url') ? raw.url : cfg.url;
    const url = explicitUrl ? normalizeUrl(explicitUrl) : await resolveTargetUrl(json);

    // Auth: explicit --auth/config wins, otherwise reuse a saved session for this host.
    let authFile: string | undefined = raw.auth ?? cfg.auth;
    if (!authFile) {
      const saved = findSavedAuth(url);
      if (saved) {
        authFile = saved;
        if (!json) console.log(chalk.dim(`  🔐 Using saved login for ${new URL(url).host}`));
      }
    }

    const fixRaw = setByCli('fix') ? raw.fix : cfg.fix;
    const opts: RoastOptions = {
      url,
      severity,
      report: pickBool('report', cfg.report, false),
      json,
      ai: pickBool('ai', cfg.ai, true),
      fast: pickBool('fast', cfg.fast, false),
      authFile,
      headers: parseHeaders(raw.header ?? cfg.headers),
      fix: fixRaw === true ? 'auto' : (fixRaw as string | undefined),
      routes: parseRoutes(raw.routes ?? cfg.routes, url),
      card: pickBool('card', cfg.card, true) && !json, // skipped for --json/--no-card
      baseline: Boolean(raw.baseline),
      saveBaseline: Boolean(raw.saveBaseline),
      reportPath: resolve(cwd, 'roast-report.html'),
      cardPath: resolve(cwd, 'roast-card.png'),
      baselinePath: resolve(cwd, 'roast-baseline.json'),
    };

    await run(opts);
  });

// `roast-my-react login` — log in once, save the session, reuse it later.
program
  .command('login')
  .description('open a browser, log in to your app, and save the session for future audits')
  .option('--url <url>', 'the app to log in to (auto-detected if omitted)')
  .action(async (raw) => {
    const url = raw.url ? normalizeUrl(raw.url) : await resolveTargetUrl(false);
    if (!isChromiumInstalled()) {
      console.log(chalk.yellow('  ⬇  Installing Chromium (one-time)…\n'));
      installChromium();
    }
    await runLogin(url);
  });

// clig.dev: "lead with examples." Shown at the end of --help.
program.addHelpText(
  'after',
  () => {
    const ex: Array<[string, string]> = [
      ['roast-my-react', 'auto-detect & roast your running app'],
      ['roast-my-react --url http://localhost:5173', 'target a specific URL'],
      ['roast-my-react --fast', 'skip Lighthouse for a ~4s run'],
      ['roast-my-react --fix', 'hand the fixes to Claude Code / Codex / opencode'],
      ['roast-my-react --routes "/,/dashboard"', 'audit several routes at once'],
      ['roast-my-react --baseline', 'compare against your saved baseline'],
      ['roast-my-react login', 'log in once for dashboards behind auth'],
    ];
    const w = Math.max(...ex.map(([c]) => c.length));
    const lines = ex.map(([c, d]) => `  ${chalk.cyan(c.padEnd(w))}  ${chalk.dim('# ' + d)}`).join('\n');
    return `\n${chalk.dim('Examples:')}\n${lines}\n`;
  }
);

program.parseAsync(process.argv).catch((err) => {
  console.error(chalk.red(`\n  ✖  ${err instanceof Error ? err.message : String(err)}\n`));
  process.exit(1);
});

/**
 * Resolve which URL to audit when the user didn't pass --url, by scanning the
 * common dev-server ports. Picks the first server found; if several are up
 * (typical in a monorepo) it tells the user and how to target the others.
 * Exits with a helpful message when nothing is running.
 */
async function resolveTargetUrl(json: boolean): Promise<string> {
  const spinner = json ? null : ora({ text: 'Reading your project config + scanning ports…', indent: 2 }).start();
  const found = await detectDevServers();

  if (found.length === 0) {
    spinner?.fail('No running dev server found');
    if (!json) printNoServerFound();
    else console.error('No running dev server found. Pass --url <url>.');
    process.exit(1);
  }

  // `found` is already ordered configured-first, so found[0] is the best guess.
  const target = found[0];

  // Interactive: show EVERY running server and let the user choose (TTY only).
  // With just one server we don't bother asking.
  if (found.length > 1 && !json && process.stdin.isTTY) {
    spinner?.stop();
    const chosen = await promptForApp(found);
    return chosen.url;
  }

  spinner?.succeed(`Found ${chalk.cyan(target.url)} ${chalk.dim(`(${describe(target)})`)}`);
  if (!json && !target.configured) {
    console.log(chalk.yellow("  ⚠  This port isn't in your project config — it may not be your app."));
    console.log(chalk.dim('     If wrong, target it explicitly: roast-my-react --url http://localhost:<port>'));
  }
  return target.url;
}

/** "web · apps/web/project.json" or just the hint when unnamed. */
function describe(s: { project?: string; hint: string }): string {
  return s.project ? `${s.project} · ${s.hint}` : s.hint;
}

/** Arrow-key picker listing every running server, recommended one first. */
async function promptForApp(servers: DetectedServer[]): Promise<DetectedServer> {
  console.log('');
  return select<DetectedServer>({
    message: `${servers.length} servers running — roast which one?`,
    initial: 0,
    choices: servers.map((s, i) => ({
      label: s.project ?? 'app',
      hint: s.url,
      badge: s.configured ? (i === 0 ? '← your app (recommended)' : '← your app') : `· ${s.hint}`,
      value: s,
    })),
  });
}

function printNoServerFound(): void {
  const ports = COMMON_PORTS.map((p) => p.port).join(', ');
  console.log('');
  console.log(chalk.red("  ✖  Couldn't find a running app on any common port."));
  console.log(chalk.dim(`     Scanned: ${ports}`));
  console.log('');
  console.log(chalk.dim('     Start your dev server first, e.g.:'));
  console.log(chalk.dim('       npm run dev      # Next.js / Vite / etc.'));
  console.log('');
  console.log(chalk.dim('     …then re-run:  ') + chalk.hex('#fb923c')('npx roast-my-react'));
  console.log(chalk.dim('     Or point it directly at your app:'));
  console.log(chalk.dim('       npx roast-my-react --url http://localhost:5173'));
  console.log('');
}

async function run(opts: RoastOptions): Promise<void> {
  if (!opts.json) renderHeader(opts.url);
  ensureChromiumOrExit(opts.json);

  const routes = opts.routes ?? [opts.url];
  const multi = routes.length > 1;

  type RouteResult = { url: string; findings: Findings; issues: Issue[] };
  let results: RouteResult[] = [];

  if (!multi) {
    // Single route: keep the live per-phase spinner.
    const spinner = opts.json ? null : ora({ text: 'Warming up…', indent: 2 }).start();
    try {
      const findings = await crawl(opts, {
        onPhase: (label) => { if (spinner) spinner.text = label; },
      });
      spinner?.succeed('Audit complete');
      results = [{ url: opts.url, findings, issues: deriveIssues(findings) }];
    } catch (err) {
      spinner?.fail('Crawl failed');
      printCrawlError(err, opts.url);
      process.exit(1);
    }
  } else {
    // Multi route: audit concurrently (each crawl gets its own isolated browser
    // + debug port), bounded so we don't melt the CPU. ~3× faster for 3+ routes.
    const spinner = opts.json ? null : ora({ text: `Auditing ${routes.length} routes in parallel…`, indent: 2 }).start();
    let done = 0;
    const audited = await mapPool(routes, 3, async (routeUrl) => {
      try {
        const findings = await crawl({ ...opts, url: routeUrl });
        return { url: routeUrl, findings, issues: deriveIssues(findings) } as RouteResult;
      } catch (err) {
        if (spinner) spinner.text = `${routePath(routeUrl)} failed: ${errText(err)}`;
        return null;
      } finally {
        done++;
        if (spinner) spinner.text = `Audited ${done}/${routes.length} routes…`;
      }
    });
    results = audited.filter((r): r is RouteResult => r !== null);
    if (results.length) spinner?.succeed(`Audited ${results.length}/${routes.length} routes`);
    else spinner?.fail('All routes failed');
  }
  if (results.length === 0) process.exit(1);

  const primary = results[0];

  // --json: dump structured data and exit.
  if (opts.json) {
    const payload = multi
      ? { routes: results.map((r) => ({ url: r.url, findings: r.findings, issues: r.issues })) }
      : { findings: primary.findings, issues: primary.issues };
    console.log(JSON.stringify(payload, null, 2));
    return;
  }

  // Scores: a per-route table for multi, the full verdict for single.
  if (multi) {
    renderRouteSummary(results.map((r) => ({ url: r.url, findings: r.findings, issueCount: r.issues.length })));
  } else {
    renderScores(primary.findings, primary.issues.length);
  }
  renderWarnings(primary.findings.warnings);

  // Combine issues across routes, worst first. An identical issue on several
  // routes is reported once, annotated with how many routes it affects.
  let combined: Issue[];
  if (multi) {
    const merged = new Map<string, { issue: Issue; routes: string[] }>();
    for (const r of results) {
      const path = routePath(r.url);
      for (const i of r.issues) {
        const entry = merged.get(i.id);
        if (entry) {
          if (!entry.routes.includes(path)) entry.routes.push(path);
          if (i.weight > entry.issue.weight) entry.issue = i;
        } else {
          merged.set(i.id, { issue: { ...i }, routes: [path] });
        }
      }
    }
    combined = [...merged.values()].map(({ issue, routes }) => ({
      ...issue,
      title:
        routes.length > 1
          ? `${issue.title} (on ${routes.length} routes: ${routes.slice(0, 3).join(', ')}${routes.length > 3 ? '…' : ''})`
          : `[${routes[0]}] ${issue.title}`,
    }));
  } else {
    combined = primary.issues;
  }
  combined.sort((a, b) => b.weight - a.weight);

  // Keep the AI call minimal: only roast the top issues.
  const issuesForAi = combined.slice(0, 14);

  let roasted: RoastedIssue[] = [];
  let aiRan = false;
  if (opts.ai && issuesForAi.length > 0) {
    const aiSpinner = ora({ text: 'Asking the AI to be mean…', indent: 2 }).start();
    try {
      roasted = await roastIssues(issuesForAi, opts.severity);
      aiRan = true;
      aiSpinner.succeed('Roast delivered');
    } catch (err) {
      if (err instanceof MissingApiKeyError) {
        aiSpinner.stop();
        renderMissingKeyNotice();
      } else {
        aiSpinner.fail(`AI step failed: ${err instanceof Error ? err.message : String(err)}`);
        console.log(chalk.dim('  Falling back to raw findings.'));
      }
    }
  }

  if (aiRan) renderRoasts(roasted);
  else renderRawFindings(combined);

  // The issue set used for report/card/fix (roasted if available, else bare).
  const decorated: RoastedIssue[] = aiRan
    ? roasted
    : combined.map((i) => ({ ...i, roast: i.title, fix: '' }));

  let reportPath: string | undefined;
  if (opts.report) {
    try {
      reportPath = await writeReport(opts.reportPath, primary.findings, decorated);
    } catch (err) {
      console.log(chalk.yellow(`  ⚠  Could not write report: ${errText(err)}`));
    }
  }

  let cardPath: string | undefined;
  if (opts.card) {
    const cardSpinner = ora({ text: 'Rendering shareable card…', indent: 2 }).start();
    try {
      cardPath = await renderCard(primary.findings, decorated, opts.cardPath);
      cardSpinner.succeed('Card ready');
    } catch (err) {
      cardSpinner.fail(`Could not render card: ${errText(err)}`);
    }
  }

  // Baseline compare / save.
  if (opts.baseline || opts.saveBaseline) {
    const snapshot = buildSnapshot(primary.findings, combined.length, new Date().toISOString());
    if (opts.baseline) {
      const prev = loadBaseline(opts.baselinePath);
      if (prev) renderComparison(prev, snapshot);
      else console.log(chalk.dim('  No baseline yet — run with --save-baseline first.'));
    }
    if (opts.saveBaseline) {
      saveBaseline(opts.baselinePath, snapshot);
      console.log(chalk.green(`  ✔  Baseline saved to ${opts.baselinePath}`));
    }
  }

  renderFooter({ reportPath, cardPath });

  // Hand off to a coding agent to actually fix the issues.
  if (opts.fix && decorated.length) {
    const result = handOffToAgent(primary.findings, decorated, opts.fix);
    if (!result.launched) {
      console.log(chalk.yellow('  🤖  No coding agent found on PATH (tried claude, codex, opencode).'));
      console.log(chalk.dim(`      Fix prompt written to ${result.promptPath}`));
      console.log(chalk.dim('      Open it with your agent, e.g.:  claude "$(cat roast-fixes.md)"'));
      console.log('');
    }
  } else if (!opts.fix && decorated.length) {
    console.log(chalk.dim('  💡 Tip: add ') + chalk.hex('#fb923c')('--fix') + chalk.dim(' to send these to Claude Code / Codex / opencode.'));
    console.log('');
  }
}

/** Install Chromium on first run so `npx roast-my-react` works with zero setup. */
function ensureChromiumOrExit(json: boolean): void {
  if (isChromiumInstalled()) return;
  if (!json) console.log(chalk.yellow('  ⬇  First run: installing Chromium (~120 MB, one-time)…\n'));
  try {
    installChromium();
  } catch (err) {
    console.log(chalk.red(`\n  ✖  Could not install Chromium automatically: ${errText(err)}`));
    console.log(chalk.dim('     Run it manually once:  npx playwright install chromium\n'));
    process.exit(1);
  }
}

/** Run `fn` over `items` with at most `limit` running concurrently, preserving order. */
async function mapPool<T, R>(items: T[], limit: number, fn: (item: T) => Promise<R>): Promise<R[]> {
  const results = new Array<R>(items.length);
  let next = 0;
  const workers = Array.from({ length: Math.min(limit, items.length) }, async () => {
    while (next < items.length) {
      const i = next++;
      results[i] = await fn(items[i]);
    }
  });
  await Promise.all(workers);
  return results;
}

/** "/dashboard" from a full URL, for compact display + tagging. */
function routePath(url: string): string {
  try {
    const u = new URL(url);
    return (u.pathname || '/') + (u.search || '');
  } catch {
    return url;
  }
}

function clampSeverity(value: string): Severity {
  const n = Number.parseInt(value, 10);
  if (n === 1 || n === 3) return n;
  return 2;
}

function normalizeUrl(url: string): string {
  if (!/^https?:\/\//i.test(url)) return `http://${url}`;
  return url;
}

/** Turn "/,/dashboard,/login" (or a string[]) into full URLs against the target's origin. */
function parseRoutes(raw: string | string[] | undefined, baseUrl: string): string[] | undefined {
  if (!raw) return undefined;
  const origin = new URL(baseUrl).origin;
  const parts = Array.isArray(raw) ? raw : raw.split(',');
  const routes = parts
    .map((r) => r.trim())
    .filter(Boolean)
    .map((r) => (/^https?:\/\//i.test(r) ? r : origin + (r.startsWith('/') ? r : `/${r}`)));
  return routes.length ? Array.from(new Set(routes)) : undefined;
}

/** Turn ["Authorization: Bearer x", "X-Env: dev"] into a header record. */
function parseHeaders(raw: string[] | undefined): Record<string, string> | undefined {
  if (!raw || raw.length === 0) return undefined;
  const headers: Record<string, string> = {};
  for (const entry of raw) {
    const idx = entry.indexOf(':');
    if (idx === -1) continue;
    const key = entry.slice(0, idx).trim();
    const value = entry.slice(idx + 1).trim();
    if (key) headers[key] = value;
  }
  return Object.keys(headers).length ? headers : undefined;
}

function errText(err: unknown): string {
  return err instanceof Error ? err.message : String(err);
}

function printCrawlError(err: unknown, url: string): void {
  const msg = err instanceof Error ? err.message : String(err);
  console.log('');
  if (/ECONNREFUSED|net::ERR_CONNECTION_REFUSED|Timeout.*exceeded|net::ERR/i.test(msg)) {
    console.log(chalk.red(`  ✖  Couldn't reach ${url}`));
    console.log(chalk.dim('     Is your dev server running? Try:'));
    console.log(chalk.dim('       npm run dev   # then re-run roast-my-react'));
    console.log(chalk.dim('     Or point at another URL: roast-my-react --url http://localhost:5173'));
  } else if (/Executable doesn't exist|playwright install/i.test(msg)) {
    console.log(chalk.red('  ✖  Chromium for Playwright is not installed.'));
    console.log(chalk.dim('     Run once: npx playwright install chromium'));
  } else {
    console.log(chalk.red(`  ✖  ${msg}`));
  }
  console.log('');
}
